var statistics = {
            number_of_dems: null,
            number_of_repubs: null,
            number_of_ind: null,
            D_voted_with_party: null,
            R_voted_with_party: null,
            I_voted_with_party: null,
    number_of_senators: null,
    top_attendance1: null,
    top_attendance2: null,
    top_attendance3: null,
    bottom_attendance1: null,
    bottom_attendance2: null,
    bottom_attendance3: null,
    bottom_loyalty1: null,
    bottom_loyalty2: null,
    bottom_loyalty3: null,
    top_loyalty1: null,
    top_loyalty2: null,
    top_loyalty3: null,
BPV1:null,
    BPV2:null,
    BPV3:null,
    BPV4:null,
        }